services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: order-service
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - APP_ENV=prod
      - APP_SECRET=${APP_SECRET:-change_this_secret}
      - SERVER_PORT=${SERVER_PORT:-8080}
    restart: unless-stopped
